name: Build and deploy Python app to Azure Web App - lumet-ia

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Usa una versión estable para producción

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare deployment package
        run: |
          mkdir package
          shopt -s extglob
          cp -r !(venv|__pycache__|.git|.github|package|release.zip|*.zip) package/
          cd package
          zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Extract artifact
        run: unzip release.zip

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_146B089416054D6B96A5CDBC6F185A5D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9844CCA7858444B48A7445A05309D121 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D67D6FD0F8F1464CAF64AE540E1CC51E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lumet-ia'
          slot-name: 'Production'
          package: .
